cookin/app/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # ex: /app/recipes/5/
    url(r'^recipes/(?P<recipe_id>[0-9]+)/?$', views.recipe_detail, name='recipe_detail'),
    url(r'^recipes/new/?$', views.add_new_recipe, name='add_new_recipe'),
    url(r'^register/?$', views.register, name='register'),
    url(r'^login/?$', views.user_login, name='login'),
    url(r'^logout/?$', views.user_logout, name='logout'),
    url(r'^recipes/(?P<recipe_id>[0-9]+)/update/?$', views.recipe_update, name='recipe_update'),
    url(r'^my-recipes/?$', views.my_recipes, name='my-recipes'),
]

cookin/cookin/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^app/', include('app.urls')),
    url(r'', 'app.views.index'),
]

cookin/app/models/ingredient_in_recipe_model.py
from django.db import models

from .recipe_model import Recipe
from .ingredient_model import Ingredient
from django.core.validators import MinValueValidator


class Ingredient_In_Recipe(models.Model):
    recipe = models.ForeignKey(Recipe)
    ingredient = models.ForeignKey(Ingredient)
    num_units = models.FloatField(validators=[MinValueValidator(0)])
    unit_name = models.CharField(max_length=32, default="")

    def __str__(self):
        return '%s: %d %s' % (self.recipe.recipe_title, self.num_units,
                self.ingredient.ingredient_name)

    class Meta:
        app_label = 'app'

cookin/app/models/recipe_model.py
from django.db import models
from django.utils import timezone
from django.core.validators import MinValueValidator
from django.utils.text import slugify
from django.db.models import Avg
import uuid
import os

from .ingredient_model import Ingredient
from taggit.managers import TaggableManager
from taggit.models import TaggedItemBase


class TaggedDietaryRestriction(TaggedItemBase):
    content_object = models.ForeignKey('Recipe')


class TaggedRecipe(TaggedItemBase):
    content_object = models.ForeignKey('Recipe')


class TaggedTool(TaggedItemBase):
    content_object = models.ForeignKey('Recipe')


def recipe_image_name(instance, filename):
    extension = os.path.splitext(filename)[1]
    return "recipe_images/%s%s" % (uuid.uuid4(), extension)


class Recipe(models.Model):
    recipe_title = models.CharField(db_index=True, max_length=200)
    recipe_text = models.TextField(default="Share your recipe instructions here!")
    recipe_image = models.ImageField(upload_to=recipe_image_name,
                                     blank=True)
    publish_date = models.DateTimeField(default=timezone.now)
    recipe_ingredients = models.ManyToManyField(Ingredient,
            through='Ingredient_In_Recipe')
    num_servings = models.IntegerField(default=1,
                                       validators=[MinValueValidator(1)])

    # total time will be a sum of the following two fields
    prep_time_minutes = models.PositiveIntegerField(default=0)
    cooking_time_minutes = models.PositiveIntegerField(default=0)

    estimated_cost = models.PositiveIntegerField(default=0)

    recipe_tags = TaggableManager(through=TaggedRecipe,
                                  related_name="recipe_tags",
                                  blank=True)
    dietary_restrictions = TaggableManager(through=TaggedDietaryRestriction,
                                           related_name="dietary_restrictions",
                                           blank=True)
    tools = TaggableManager(through=TaggedTool,
                            related_name="tools",
                            blank=True)
    recipe_owner = models.ForeignKey('UserProfile', blank=True, null=True,
                                        related_name='owner_recipe')

    def __str__(self):
        return '%s: %s' % (self.recipe_title, self.recipe_text)

    def total_time(self):
        return self.prep_time_minutes + self.cooking_time_minutes

    def average_cost_estimate_per_serving(self):
        cost = self.estimated_cost
        recipe_ratings = self.ratings.all()
        cost_sum = 0
        num_estimates = 0
        if cost:
            cost_sum += (cost / self.num_servings)
            num_estimates += 1
        for rating in recipe_ratings:
            if rating.rating_price:
                cost_sum += rating.rating_price / rating.rating_num_servings
                num_estimates += 1
        if not num_estimates:
            return 0
        return cost_sum / num_estimates

    def average_cost_estimate(self):
        def truncate_2_places(x):
            return int(x * 100)/100

        return truncate_2_places(self.average_cost_estimate_per_serving() * self.num_servings)

    def relevance(self, my_tools=[], sort_by = ""):
        def sort_relevance(sort_param):
            if sort_param == 'cost' and self.average_cost_estimate_per_serving() == 0:
                return -1000000
            fields = {
                "time":-self.total_time(),
                "cost":-self.average_cost_estimate_per_serving(),
                "rating":self.average_rating()
            }
            if sort_param in fields:
                return fields[sort_param]
            return 0

        score = 0
        if my_tools:
            my_tools = map(slugify, my_tools)
            recipe_tools = self.tools.slugs()
            for tool in recipe_tools:
                if tool in my_tools:
                    score += 1
                else:
                    score -= 1

        score += sort_relevance(sort_by) * .01
        return score



    def average_rating(self):
        qs = self.ratings.all()
        if len(qs) > 0:
            return qs.aggregate(Avg('rating_stars'))['rating_stars__avg']
        return 0

    class Meta:
        app_label = 'app'

cookin/app/views/add_new_recipe_view.py
from django.shortcuts import redirect, render
from app.models import Recipe, Ingredient, Ingredient_In_Recipe
from app.forms import AddRecipeForm
from app.views import recipe_detail
from django.contrib.auth.decorators import login_required

@login_required
def add_new_recipe(request):
    valid = True

    if request.method == "POST":
        form = AddRecipeForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save()

            post.recipe_owner = request.user.profile

            tags = form.cleaned_data.get('recipe_tags').lower().split(',')
            for tag in tags:
                post.recipe_tags.add(tag.strip())

            tools = form.cleaned_data.get('tools').lower().split(',')
            for tool in tools:
                post.tools.add(tool.strip())

            restrs = form.cleaned_data.get('dietary_restrictions').lower().split(',')
            for restr in restrs:
                post.dietary_restrictions.add(restr.strip())

            ings = form.cleaned_data.get('recipe_ingredients').split("|")
            for ing in ings:
                data = ing.split(":")
                ingredient, created = Ingredient.objects.get_or_create(ingredient_name=data[0].lower())
                num = data[1].strip()
                unit = data[2].strip()
                relation = Ingredient_In_Recipe(recipe=post,
                                                ingredient=ingredient,
                                                num_units=num)
                if len(unit) > 1:
                    relation.unit_name = unit
                relation.save()

            post = form.save()
            return redirect(recipe_detail, recipe_id=post.pk)
        else:
            valid = False
    else:
        form = AddRecipeForm()

    return render(request,
                  'recipes/add_new_recipe_form.html',
                  {'form': form, 'valid': valid})

cookin/app/views/recipe_detail.py
from django.shortcuts import get_object_or_404, render
from app.models import Recipe


def recipe_detail(request, recipe_id):
    recipe = get_object_or_404(Recipe, pk=recipe_id)
    return render(request, 'recipe_detail.html', {'recipe': recipe})

cookin/app/views/recipe_detail_view.py
from django.shortcuts import get_object_or_404, render
from app.models import Recipe, Rating, UserProfile
from app.forms import RatingForm
from django.shortcuts import redirect


def recipe_detail(request, recipe_id):
    recipe = get_object_or_404(Recipe, pk=recipe_id)
    form = RatingForm(request.POST or None)
    if form.is_valid():
        rating = form.save(commit=False)
        rating.rating_recipe = recipe
        rating.rating_user = request.user.profile
        rating.save()
        return redirect(request.path)
    return render(request, 'recipes/recipe_detail.html',
                  {'recipe': recipe, 'form': form})

cookin/app/views/recipe_update_view.py
from django.shortcuts import get_object_or_404, render, redirect
from django.views.generic import UpdateView
from app.views import recipe_detail
from app.models import Recipe, Ingredient, Ingredient_In_Recipe
from app.forms import AddRecipeForm
from django.template import RequestContext

def recipe_update(request, recipe_id):
    valid = True
    if request.POST:
        form = AddRecipeForm(request.POST, request.FILES)
        if form.is_valid():
            recipe = get_object_or_404(Recipe, pk=recipe_id)
            form = AddRecipeForm(request.POST, instance = recipe)
            post = form.save()

            post.recipe_tags.clear()
            tags = form.cleaned_data.get('recipe_tags').lower().split(',')
            for tag in tags:
                post.recipe_tags.add(tag.strip())

            post.tools.clear()
            tools = form.cleaned_data.get('tools').lower().split(',')
            for tool in tools:
                post.tools.add(tool.strip())

            post.dietary_restrictions.clear()
            restrs = form.cleaned_data.get('dietary_restrictions').lower().split(',')
            for restr in restrs:
                post.dietary_restrictions.add(restr.strip())

            post.recipe_ingredients.clear()
            ings = form.cleaned_data.get('recipe_ingredients').split("|")
            for ing in ings:
                data = ing.split(":")
                ingredient, created = Ingredient.objects.get_or_create(ingredient_name=data[0].lower())
                num = data[1].strip()
                unit = data[2].strip()
                relation = Ingredient_In_Recipe(recipe=post,
                                                ingredient=ingredient,
                                                num_units=num)
                if len(unit) > 1:
                    relation.unit_name = unit
                relation.save()

            return redirect(recipe_detail, recipe_id=recipe_id)
        else:
            valid = False

    recipe = Recipe.objects.get(pk=recipe_id)
    ingredients_list = recipe.ingredient_in_recipe_set.all()
    ingredients = '|'.join([x.ingredient.ingredient_name + ":" + str(x.num_units) + ":" + x.unit_name for x in ingredients_list])
    form = AddRecipeForm(instance = recipe)

    return render(request, 'recipes/recipe_update.html',
        {'recipe': recipe, 'form': form, 'ingredients': ingredients, 'valid': valid},
        context_instance=RequestContext(request))

cookin/app/templates/recipes/add_new_recipe_form.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
<div class="page-header">
    <h1>Add a New Recipe!</h1>
</div>

    {% if not valid %}
    <div class="alert alert-warning alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <strong>Please enter valid information!</strong>
    </div>
    {% endif %}

    <form enctype="multipart/form-data" method="post" action="">
        {% csrf_token %}

        {% bootstrap_label "Recipe Title" label_for="id_recipe_title" %}
        {% bootstrap_field form.recipe_title show_label=False %}

        {% bootstrap_label "Recipe Text" label_for="id_recipe_text" %}
        {% bootstrap_field form.recipe_text show_label=False %}

        {% bootstrap_label "Prep time (minutes)" label_for="id_prep_time_minutes" %}
        {% bootstrap_field form.prep_time_minutes show_label=False %}

        {% bootstrap_label "Cooking time (minutes)" label_for="id_cooking_time_minutes" %}
        {% bootstrap_field form.cooking_time_minutes show_label=False %}

        <input class="hidden-field" id="id_recipe_ingredients" name="recipe_ingredients" type="text" readonly="readonly">

        <label>Ingredients</label>
        <div id="ing-container">
            <div id="ing-0" class="form-group">
                <div class="input-group">
                    <span class="input-group-addon" id="ing-name-0">Name:</span>
                    <input type="text" class="form-control" aria-describedby="ing-name-0" required="required">
                    <span class="input-group-addon" id="ing-num-0">Amount:</span>
                    <input type="number" step="any" class="form-control" aria-describedby="ing-num-0" required="required">
                    <span class="input-group-addon" id="ing-unit-0">Units:</span>
                    <input type="text" class="form-control" placeholder="optional" aria-describedby="ing-unit-0">
                </div>
            </div>
        </div>
        <div class="form-group">
            <span id="ing-add" class="btn btn-default">Add Ingredient</span>
        </div>

        {% bootstrap_label "Estimated cost (dollars)" label_for="id_estimated_cost" %}
        {% bootstrap_field form.estimated_cost show_label=False %}

        {% bootstrap_label "Number of Servings" label_for="id_num_servings" %}
        {% bootstrap_field form.num_servings show_label=False %}

        {% bootstrap_label "Tools (comma separated)" label_for="id_tools" %}
        {% bootstrap_field form.tools show_label=False %}

        {% bootstrap_label "Satisfied Dietary Restrictions (comma separated)" label_for="id_dietary_restrictions" %}
        {% bootstrap_field form.dietary_restrictions show_label=False %}

        {% bootstrap_label "Tags (comma separated)" label_for="id_recipe_tags" %}
        {% bootstrap_field form.recipe_tags show_label=False %}
        {% bootstrap_label "Image Upload" label_for="" %}
        {% bootstrap_field form.recipe_image show_label=False %}

        <button class="btn btn-primary" type="submit" id="submit_recipe">Submit</button>
    </form>
{% endblock %}

{# Tell django we're using static files #}
{% load staticfiles %}
{# Attach a js file! #}
{% block javascript %}
<script type="text/javascript" src="{% static "ingredient_input.js" %}"></script>
{% endblock %}

cookin/app/templates/recipes/recipe_detail.html
{# Tell django what the base template is #}
{% extends "base.html" %}

{# laod the django package's form helpers #}
{% load bootstrap3 %}

{# Title of page to be displayed on browser tab: Cookin | <title of recipe> #}
{% block title %}{{ recipe.recipe_title }}{% endblock %}

{# All content of this page goes in the 'content' block #}
{% block content %}
<div class="page-header">
    <h1>{{ recipe.recipe_title }}
    {% if user.profile == recipe.recipe_owner %}
    <a href="{% url 'recipe_update' recipe_id=recipe.id %}" class="btn btn-default">Update This Recipe</a>
    {% endif %}
    </h1>

    <p>Written by {{ recipe.recipe_owner }}</p>
    <!-- Add edit recipe functionality -->
</div>
{# bootstrap content goes in rows! (then columns) #}
<div class="row">
    {% if recipe.recipe_image %}
    <div class="col-sm-5">
        <img src="{{ MEDIA_URL }}{{recipe.recipe_image}}" class="img-responsive img-thumbnail center-block recipe-detail-img" alt=""/>
    </div>
    <div class="col-sm-7">
    {% else %}
    <div class="col-sm-12">
    {% endif %}
        <div class="row">
            <div class="col-sm-12">
                <h3>General Info</h3>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <p>Average rating: {{recipe.average_rating.rating_stars__avg}}</p>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <p>Number of servings: {{recipe.num_servings}}</p>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <p>Prep time: {{recipe.prep_time_minutes}} minutes</p>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <p>Cooking time: {{recipe.cooking_time_minutes}} minutes</p>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <p>Estimated cost: {{recipe.estimated_cost}} dollars</p>
                <p>Total time: {{recipe.total_time}} minutes</p>
            </div>
        </div>
        {% if recipe.tools.all %}
        <div class="row">
            <div class="col-sm-12">
                <h3>Tools</h3>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <ul class="list-inline">
                    {% for tool in recipe.tools.all %}
                    <li>{{ tool }}</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        {% endif %}

        {% if recipe.dietary_restrictions.all %}
        <div class="row">
            <div class="col-sm-12">
                <h4>Satisfied Dietary Restrictions</h4>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <ul class="list-inline">
                    {% for restriction in recipe.dietary_restrictions.all %}
                    <li>{{ restriction }}</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        {% endif %}

        {% if recipe.recipe_tags.all %}
        <div class="row">
            <div class="col-sm-12">
                <h4>Tags</h4>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <ul class="list-inline">
                    {% for tag in recipe.recipe_tags.all %}
                    <li>{{ tag }}</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        {% endif %}
    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        <h3>Directions</h3>
    </div>
</div>
<div class="row">
    <div class="col-sm-12">
        <p>{{recipe.recipe_text | linebreaksbr}}</p>
    </div>
</div>

{% if recipe.ingredient_in_recipe_set.all %}
<div class="row">
    <div class="col-sm-12">
        <h3>Ingredients</h3>
    </div>
</div>
<div class="row">
    <div class="col-sm-12">
        <ul>
            {% for ingredient in recipe.ingredient_in_recipe_set.all %}
            <li>
            {{ ingredient.ingredient }} - {{ ingredient.num_units }} {{ ingredient.unit_name }}
            </li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endif %}

<!-- display comments -->
{% if recipe.ratings.all %}
<div class="row">
    <div class="col-sm-12">
        <h3>Comments</h3>
    </div>
</div>
<div class="row">
    <div class="col-sm-12">
        {% for rating in recipe.ratings.all %}
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h4 class="panel-title">{{ rating.rating_user.user.username }} said on {{ rating.rating_date|date:"D M jS" }}: </h4>
            </div>
            <div class="panel-body">
                {% if rating.rating_image %}
                <div class="col-sm-3">
                    <div class="thumbnail">
                        <img src="{{ MEDIA_URL }}{{rating.rating_image}}" width="50%" alt=""/>
                    </div>
                </div>
                <div class="col-sm-9">
                {% else %}
                <div class="col-sm-12">
                {% endif %}
                    <p>
                    {{ rating.rating_comment }}
                    </p>
                    <p>
                    Rating: {{ rating.rating_stars }} of 5
                    </p>
                    <p>
                    Price: {{ rating.rating_price }} dollars
                    </p>
                    <p>
                    Made {{ rating.rating_num_servings }} servings
                    </p>
                </div>
            </div>
        </div>
        {% endfor %}
        </ul>
    </div>
</div>
{% endif %}


<!-- Add comment only if user is logged in-->
{% if user.is_authenticated %}
<div class="row">
    <div class="col-sm-12">
        <h3>Add Comment</h3>
    </div>
</div>
<div class="row">
    <form action="" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% bootstrap_button "Submit" name="submit" button_type='submit' %}
    </form>
</div>
{% else %}
<div class="row">
    <div class="col-sm-12">
        {% bootstrap_button "Register" button_type='button' href="/app/register/" button_class='btn-default' %}
        or
        {% bootstrap_button "Login" button_type='button' href="/app/login/" button_class='btn-default' %}
        to comment.
    </div>
</div>
{% endif %}





{% endblock %}

cookin/app/templates/recipes/recipe_update.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
<div class="page-header">
    <h1>Edit Recipe!</h1>
</div>

    {% if not valid %}
    <div class="alert alert-warning alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <strong>Please enter valid information!</strong>
    </div>
    {% endif %}

    <form enctype="multipart/form-data" method="post" action="">
        {% csrf_token %}

        {% bootstrap_label "Recipe Title" label_for="id_recipe_title" %}
        {% bootstrap_field form.recipe_title show_label=False %}

        {% bootstrap_label "Recipe Text" label_for="id_recipe_text" %}
        {% bootstrap_field form.recipe_text show_label=False %}

        {% bootstrap_label "Prep time (minutes)" label_for="id_prep_time_minutes" %}
        {% bootstrap_field form.prep_time_minutes show_label=False %}

        {% bootstrap_label "Cooking time (minutes)" label_for="id_cooking_time_minutes" %}
        {% bootstrap_field form.cooking_time_minutes show_label=False %}

        <input class="hidden-field" id="id_recipe_ingredients" name="recipe_ingredients" type="text" readonly="readonly" value="{{ingredients}}">

        <label>Ingredients</label>
        <div id="ing-container">
        </div>
        <div class="form-group">
            <span id="ing-add" class="btn btn-default">Add Ingredient</span>
        </div>

        {% bootstrap_label "Estimated cost (dollars)" label_for="id_estimated_cost" %}
        {% bootstrap_field form.estimated_cost show_label=False %}

        {% bootstrap_label "Number of Servings" label_for="id_num_servings" %}
        {% bootstrap_field form.num_servings show_label=False %}

        <div class="form-group">
            {% bootstrap_label "Tools (comma separated)" label_for="id_tools" %}
            <input type="text" class="form-control" id="id_tools" name="tools"
            value="{{ recipe.tools.all | join:", " }}">
        </div>

        <div class="form-group">
            {% bootstrap_label "Satisfied Dietary Restrictions (comma separated)" label_for="id_dietary_restrictions" %}
            <input type="text" class="form-control" id="id_dietary_restrictions" name="dietary_restrictions"
            value="{{ recipe.dietary_restrictions.all | join:", " }}">
        </div>

        <div class="form-group">
            {% bootstrap_label "Tags (comma separated)" label_for="id_recipe_tags" %}
            <input type="text" class="form-control" id="id_recipe_tags" name="recipe_tags"
            value="{{ recipe.recipe_tags.all | join:", " }}">
        </div>

        {% bootstrap_label "Image Upload" label_for="" %}
        {% bootstrap_field form.recipe_image show_label=False %}

        <button class="btn btn-primary" type="submit" id="submit_recipe">Submit</button>
    </form>
{% endblock %}

{# Tell django we're using static files #}
{% load staticfiles %}
{# Attach a js file! #}
{% block javascript %}
<script type="text/javascript" src="{% static "ingredient_input.js" %}"></script>
{% endblock %}

cookin/app/templates/recipes/update_success.html
<h1>Update Success</h1>